name = "Standard ML"
grammar = "sml"
path_suffixes = ["sml", "sig", "fun"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },

    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
tab_size = 2
block_comment = ["(* ", " *)"]
